name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -ldflags "-s -w" -o "myapp-{{ matrix.os }}-{{ matrix.arch }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp-{{ matrix.os }}-{{ matrix.arch }}
          path: myapp-{{ matrix.os }}-{{ matrix.arch }}
