name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [windows, macos]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        platform: ${{ matrix.platform }}

    - name: Build for ${{ matrix.platform }}/${{ matrix.arch }}
      run: GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -o myprogram-${{ matrix.platform }}-${{ matrix.arch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myprogram-${{ matrix.platform }}-${{ matrix.arch }}
        path: myprogram-${{ matrix.platform }}-${{ matrix.arch }}
